#ifndef WEIGHTLIFTING_GLOBAL_H
#define WEIGHTLIFTING_GLOBAL_H

#include <QLoggingCategory>
#include <qglobal.h>

#if defined(WEIGHTLIFTING_LIBRARY)
#  define WEIGHTLIFTING_EXPORT Q_DECL_EXPORT
#else
#  define WEIGHTLIFTING_EXPORT Q_DECL_IMPORT
#endif

Q_DECLARE_LOGGING_CATEGORY(weightliftingLog)

#endif // WEIGHTLIFTING_GLOBAL_H
